apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: neo4j
  labels:
    component: neo4j
spec:
  serviceName: neo4j
  replicas: 1
  template:
    metadata:
      labels:
        component: neo4j
    spec:
      initContainers:
      - name: sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: neo4j
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: neo4j:3.2-enterprise
        imagePullPolicy: Always
        resources:
          limits:
            memory: "2048Mi"
            cpu: "1000m"
          requests:
            memory: "1536Mi"
        env:
        - name: NEO4J_AUTH
          value: "neo4j/none"
        - name: NEO4J_dbms_memory_heap_max__size
          value: "1024M"
        - name: NEO4J_dbms_memory_heap_initial__size
          value: "1024M"
        - name: NEO4J_dbms_threads_worker__count
          value: "5"
        - name: NEO4J_dbms_shell_enabled
          value: "true"
        - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
          value: "yes"
        ports:
        - containerPort: 7687
          name: transport
          protocol: TCP
        - containerPort: 7474
          name: web
          protocol: TCP
        volumeMounts:
        - name: neo4j-storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: neo4j-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
