apiVersion: v1
kind: Service
metadata:
  name: neo4j-instance
  labels:
    component: neo4j-instance
spec:
  ports:
  - port: 6362
    name: backups
  - port: 7687
    name: transport
  - port: 7474
    name: web
  selector:
    component: neo4j-instance
