apiVersion: v1
kind: Service
metadata:
  name: neo4j-web
  labels:
    component: neo4j
spec:
  type: LoadBalancer
  ports:
  - port: 7687
    name: transport
  - port: 80
    targetPort: 7474
    name: web
  selector:
    component: neo4j
