apiVersion: v1
kind: Service
metadata:
 labels:
   name: control-tower
 name: control-tower
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 9000
    nodePort: 31000
    targetPort: 9000
  selector:
    name: control-tower

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: control-tower
  name: control-tower
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: control-tower
    spec:
      containers:
      - name: control-tower
        image: rrequero/control-tower:1.0.1
        args:
          - develop
        env:
          - name: PORT
            value: "9000"
          - name: LOGGER_TYPE
            value: console
          - name: NODE_ENV
            value: dev
          - name: NODE_PATH
            value: app/src
          - name: EXEC_MIGRATION
            value: "true"
          - name: JWT_SECRET
            value: mysecret
          - name: SESSION_KEY
            value: test
        ports:
          - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP

      restartPolicy: Always
