apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: control-tower
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: control-tower
    spec:
      containers:
      - args:
        - develop
        env:
        - name: PORT
          value: "9000"
        - name: LOGGER_TYPE
          value: console
        - name: NODE_ENV
          value: dev
        - name: NODE_PATH
          value: app/src
        - name: EXEC_MIGRATION
          value: "true"
        - name: JWT_SECRET
          value: mysecret
        - name: SESSION_KEY
          value: test
        name: control-tower
        ports:
        - containerPort: 9000
        image: rrequero/control-tower:1.0.1

        readinessProbe:
        # an http probe
          httpGet:
            path: /healthz
            port: 9000
            scheme: HTTP
      restartPolicy: Always
