apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: control-tower-cron
  name: control-tower-cron
spec:
  template:
    metadata:
      labels:
        name: control-tower-cron
    spec:
      containers:
      - name: control-tower-cron
        image: apihighways/control-tower:1.0.52-data4sdgs-cron
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "9000"
          - name: LOGGER_TYPE
            value: console
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: BASICAUTH_USERNAME
            value: vizzuality
          - name: CONFIRM_URL_REDIRECT
            value: http://apihighways.data4sdgs.org/
          - name: PUBLIC_URL
            value: http://load.apihighways.org
          - name: APP_NAME
            value: "APIHighways"
          - name: APP_LOGO
            value: https://apihighways.org/static/logos/logo-api-highways.svg
          - name: APP_COLOR
            value: "#212020"
          - name: CT_MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: CT_MONGO_URI
          - name: SESSION_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: SESSION_KEY
          - name: JWT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: JWT_SECRET
          - name: BASICAUTH_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: BASICAUTH_PASSWORD
          - name: SPARKPOST_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: SPARKPOST_KEY
        args:
          - startCron
      restartPolicy: Always


