apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: control-tower
  name: control-tower
spec:
  template:
    metadata:
      labels:
        name: control-tower
    spec:
      containers:
      - name: control-tower
        image: rrequero/control-tower:1.0.8
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "1Gi"
        args:
          - startDev
        env:
          - name: PORT
            value: "9000"
          - name: LOGGER_TYPE
            value: console
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: BASICAUTH_USERNAME
            value: vizzuality
          - name: CONFIRM_URL_REDIRECT
            value: http://www.globalforestwatch.org
          - name: PUBLIC_URL
            value: http://production-api.globalforestwatch.org
          - name: CT_MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: CT_MONGO_URI
          - name: SESSION_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: SESSION_KEY
          - name: JWT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: JWT_SECRET
          - name: TWITTER_CONSUMER_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: TWITTER_CONSUMER_KEY
          - name: TWITTER_CONSUMER_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: TWITTER_CONSUMER_SECRET
          - name: FACEBOOK_CLIENT_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: FACEBOOK_CLIENT_ID
          - name: FACEBOOK_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: FACEBOOK_CLIENT_SECRET
          - name: GOOGLE_CLIENT_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: GOOGLE_CLIENT_ID
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: GOOGLE_CLIENT_SECRET
          - name: BASICAUTH_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: BASICAUTH_PASSWORD
          - name: SPARKPOST_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: SPARKPOST_KEY
          - name: INSTAPUSH_TOKEN
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: INSTAPUSH_TOKEN
          - name: INSTAPUSH_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: INSTAPUSH_ID
          - name: INSTAPUSH_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: INSTAPUSH_SECRET

        ports:
          - containerPort: 9000
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15

      restartPolicy: Always
