apiVersion: v1
kind: Service
metadata:
 labels:
   name: control-tower
 name: control-tower
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9000
  selector:
    name: control-tower

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: control-tower
  name: control-tower
spec:
  template:
    metadata:
      labels:
        name: control-tower
    spec:
      containers:
      - name: control-tower
        image: rrequero/control-tower:1.0.30
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "1Gi"
        args:
          - startDev
        env:
          - name: PORT
            value: "9000"
          - name: LOGGER_TYPE
            value: console
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: BASICAUTH_USERNAME
            value: vizzuality
          - name: CONFIRM_URL_REDIRECT
            value: http://www.globalforestwatch.org
          - name: PUBLIC_URL
            value: http://production-api.globalforestwatch.org
          - name: APP_NAME
            value: "WRI API"
          - name: APP_LOGO
            value: http://www.wri.org/sites/all/themes/wri/images/logo.png
          - name: APP_COLOR
            value: "#f1b319"
          - name: CT_MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: CT_MONGO_URI
          - name: SESSION_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: SESSION_KEY
          - name: JWT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: JWT_SECRET
          - name: TWITTER_CONSUMER_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: TWITTER_CONSUMER_KEY
          - name: TWITTER_CONSUMER_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: TWITTER_CONSUMER_SECRET
          - name: FACEBOOK_CLIENT_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: FACEBOOK_CLIENT_ID
          - name: FACEBOOK_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: FACEBOOK_CLIENT_SECRET
          - name: GOOGLE_CLIENT_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: GOOGLE_CLIENT_ID
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: GOOGLE_CLIENT_SECRET
          - name: BASICAUTH_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: BASICAUTH_PASSWORD
          - name: SPARKPOST_KEY
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: SPARKPOST_KEY
          - name: INSTAPUSH_TOKEN
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: INSTAPUSH_TOKEN
          - name: INSTAPUSH_ID
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: INSTAPUSH_ID
          - name: INSTAPUSH_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: INSTAPUSH_SECRET

        ports:
          - containerPort: 9000
      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: control-tower
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: control-tower
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
