apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: control-tower
  name: control-tower
spec:
  template:
    metadata:
      labels:
        name: control-tower
    spec:
      containers:
      - name: control-tower
        image: rrequero/control-tower:1.0.3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "1Gi"
        args:
          - develop
        env:
          - name: PORT
            value: "9000"
          - name: LOGGER_TYPE
            value: console
          - name: NODE_ENV
            value: dev
          - name: NODE_PATH
            value: app/src
          - name: EXEC_MIGRATION
            value: "true"
          - name: SESSION_KEY
            value: test
          - name: JWT_SECRET
            valueFrom:
                secretKeyRef:
                  name: ctsecrets
                  key: JWT_SECRET

        ports:
          - containerPort: 9000
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 15

      restartPolicy: Always
