apiVersion: v1
kind: Service
metadata:
  labels:
    name: dataset
  name: dataset
spec:
  ports:
    - port: 3000
  selector:
    name: dataset

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: dataset
  name: dataset
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: dataset
    spec:
      containers:
      - name: dataset
        image: vizzuality/dataset:1.1.5
        args:
          - develop
        env:
          - name: PORT
            value: "3000"
          - name: NODE_ENV
            value: dev
          - name: NODE_PATH
            value: app/src
          - name: S3_ACCESS_KEY_ID
            value: access_key
          - name: S3_SECRET_ACCESS_KEY
            value: secret_key
          - name: NEWRELIC_LICENSE
            value: test
          - name: WORKERS
            value: "1"
          - name: GATEWAY_URL
            value: http://10.15.241.135:80
          - name: CT_URL
            value: http://10.15.241.135:80
          - name: LOCAL_URL
            value: http://10.15.252.49:3000
          - name: GATEWAY_TOKEN
            value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.eUmM_C8WNPBk8EJS3rHo2Zc4wCmYkzyRpRyK8ZzDV2U
          - name: CT_TOKEN
            value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.eUmM_C8WNPBk8EJS3rHo2Zc4wCmYkzyRpRyK8ZzDV2U
          - name: API_VERSION
            value: v1

        ports:
          - containerPort: 3000

      restartPolicy: Always
