apiVersion: v1
kind: Service
metadata:
  labels:
    name: dataset
  name: dataset
spec:
  ports:
    - port: 3000
  selector:
    name: dataset

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: dataset
  name: dataset
spec:
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: dataset
    spec:
      containers:
      - name: dataset
        image: vizzuality/dataset:1.1.5
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
        args:
          - start
        env:
          - name: PORT
            value: "3000"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: dataset.default.svc.cluster.local:3000

        ports:
          - containerPort: 3000

      restartPolicy: Always

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dataset
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: dataset
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
