apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: ubuntu
  name: ubuntu
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep"]
        args: ["100000"]
