apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: doc
  name: doc
spec:
  template:
    metadata:
      labels:
        name: doc
    spec:
      containers:
      - name: doc
        image: vizzuality/doc-swagger:0.0.4
        imagePullPolicy: Always
        ports:
          - containerPort: 80
      restartPolicy: Always

