apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data-v2
  labels:
    type: db-elastic
    component: elasticsearchV2
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: 3
  template:
    metadata:
      labels:
        type: db-elastic
        component: elasticsearchV2
        role: data
    spec:
      initContainers:
      - name: sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.5.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "3Gi"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch-discovery-v2"
        - name: "CLUSTER_NAME"
          value: "myesdbV2"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "false"
        - name: "ES_JAVA_OPTS"
          value: "-Xms3g -Xmx3g"
        - name: "ES_PLUGINS_INSTALL"
          value: "https://github.com/NLPchina/elasticsearch-sql/releases/download/5.5.0.0/elasticsearch-sql-5.5.0.1.zip,repository-s3"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: BACKUP_S3_ACCESS_KEY
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
              secretKeyRef:
                name: dbsecrets
                key: BACKUP_S3_SECRET_KEY
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        volume.beta.kubernetes.io/storage-class: gp2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 300Gi
