apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-v2
  labels:
    component: elasticsearchV2
    role: client
spec:
  type: ClusterIP
  selector:
    component: elasticsearchV2
    role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
